language: android
android:
  components:
  - build-tools-25.0.0
  - android-25
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-25
  - sys-img-armeabi-v7a-android-19
  - sys-img-x86-android-17
before_install:
- openssl aes-256-cbc -K $encrypted_606d43e01d50_key -iv $encrypted_606d43e01d50_iv
  -in store.jks.enc -out store.jks -d
